#!/usr/bin/expect 
set sortie [lindex $argv 0]
set mdpcle [lindex $argv 1]
spawn ssh-keygen 
expect "id_rsa): "
send "$sortie/id-rsa\r"
expect "no passphrase:"
send "Bienvenu chez operis\r"
expect "passphrase again:"
send "Bienvenu chez operis\r"
sleep 2
spawn chown rundeck:rundeck $sortie/id-rsa.pub
spawn chown rundeck:rundeck $sortie/id-rsa
sleep 4
interact "\r"
