#!/usr/bin/expect

set ipnoeud [lindex $argv 0]
set mdp [lindex $argv 1]
set nomduprojet [lindex $argv 2]
set valeurcle [exec cut -c1-80 /var/rundeck/projects/${nomduprojet}/etc/id-rsa.pub]

spawn ssh root@$ipnoeud sed -i \'/${valeurcle}/d\' /root/.ssh/authorized_keys

expect "password: "
send "${mdp}\r"
interact "\r"

sleep 4
